#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# run the xrandr command if an external monitor is connected
# This must be executed before the polybar command, so that
# polybar can set the two separate bars properly.
#if [ -x $HOME/.config/bspwm/bspwm_dual_monitor ]; then
#    $HOME/.config/bspwm/bspwm_dual_monitor
#fi

bspc monitor -d I II III IV V VI VII VIII IX X
#bspc monitor Virtual2 -d I II III
#bscp monitor Virtual1 -d IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

vmware-user-suid-wrapper
wmname LG3D &
feh --bg-fill /home/h4ck3df1sh/Desktop/Backgrounds/h4ck3df1sh-background.png &
~/.config/polybar/launch.sh
picom&
bspc config border_width 1
